### ISSUE TITLE
TypeError: e.flatMap(...) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by EysaDun** [ethersphere/swarm-cli#230]
```
eysir@eysir-ubu:~/workspace/golang/swarm-cli$ swarm-cli feed upload /home/eysir/swarms/Helloworld --identity 0xa252a95063b5200ce94fca44623d251ce6de5efd --password 123123 --stamp b8857b1865a9180c00febbd5a98b3c1d64630d62309550bd85d885435ed3a0ab
(node:794827) UnhandledPromiseRejectionWarning: TypeError: e.flatMap(...) is not a function or its return value is not iterable
    at findCommandByFullPath (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:633892)
    at Object.parse (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:630974)
    at m.initCommandClasses (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:662348)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:794827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:794827) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
eysir@eysir-ubu:~/workspace/golang/swarm-cli$ swarm-cli feed upload /home/eysir/swarms/Helloworld --stamp b8857b1865a9180c00febbd5a98b3c1d64630d62309550bd85d885435ed3a0ab
(node:794858) UnhandledPromiseRejectionWarning: TypeError: e.flatMap(...) is not a function or its return value is not iterable
    at findCommandByFullPath (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:633892)
    at Object.parse (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:630974)
    at m.initCommandClasses (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:662348)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:794858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:794858) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
eysir@eysir-ubu:~/workspace/golang/swarm-cli$ sudo swarm-cli feed upload /home/eysir/swarms/Helloworld --stamp b8857b1865a9180c00febbd5a98b3c1d64630d62309550bd85d885435ed3a0ab
[sudo] password for eysir: 
(node:794882) UnhandledPromiseRejectionWarning: TypeError: e.flatMap(...) is not a function or its return value is not iterable
    at findCommandByFullPath (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:633892)
    at Object.parse (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:630974)
    at m.initCommandClasses (/usr/local/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:662348)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:794882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:794882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
eysir@eysir-ubu:~/workspace/golang/swarm-cli$ 

```

**Comment by Cafe137** [comment]
Hello @EysaDun! Thank you for the report.

Any chance you are using Node.js 10 or an earlier version? `flatMap` should be available starting from Node.js 12 I think.

**Comment by Cafe137** [comment]
Hello @EysaDun! Is this still an issue for you?

**Comment by EysaDun** [comment]
> Hello @EysaDun! Is this still an issue for you?

NO，I run it as OK.
