### ISSUE TITLE
no guards against cli argument if specified twice

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#39]
i accidentally specified `topic` twice, and got unexpected results.

```
FRONT=true && swarm-cli --identity="fp-wallet" --password="..." feed upload --path "./dist" --bee-api-url http://localhost:1633 --topic "0000000000000000000000000000000000000000000000000000000000000000" --topic "0000000000000000000000000000000000000000000000000000000000000000"
```

```
TypeError: this.topic.startsWith is not a function
    at u.enforceValidHexTopic (/Users/sig/.nvm/versions/node/v14.6.0/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:1094028)
    at u.getTopic (/Users/sig/.nvm/versions/node/v14.6.0/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:1093800)
    at updateFeedAndPrint (/Users/sig/.nvm/versions/node/v14.6.0/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:1093185)
    at async u.run (/Users/sig/.nvm/versions/node/v14.6.0/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:1099114)
    at async Object.handler (/Users/sig/.nvm/versions/node/v14.6.0/lib/node_modules/@ethersphere/swarm-cli/dist/index.js:3:659211)
```

**Comment by Cafe137** [comment]
The framework parses this as an array, probably.
